# Source keybinds
source-file ~/.config/tmux/tmux.keybinds.conf

# Fix colours (not sure needed)
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides "*:RGB"
set -g mouse on

# To enable yazi preview in tmux
set -g allow-passthrough all
# set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set-environment -gu TERMINFO

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# don't exit from tmux when closing a session
set -g detach-on-destroy off	# don't exit from tmux when closing a session
set -g renumber-windows on	# renumber all windows when any window is closed
set -g set-clipboard on		# use system clipboard
set -g status-position top      # move tmux status line to the top
# set -g default-terminal "${TERM}"	# Ensure zsh terminal emulation
setw -g mode-keys vi		# Set vi keys in copy-mode

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'omerxx/tmux-floax'

# Floax config
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

# Continuum & resurrect
set -g @continuum-boot 'on' # Automatically start tmux server when computer is turned on
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# UI customizations
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# Catppuccin (v2) theme options
set -g @catppuccin_flavor 'macchiato'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number "#I"
set -g @catppuccin_window_flags "none"


set -g @catppuccin_status_left_separator " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"

# Load catppuccin synchronously before composing status-right (v2 requirement)
set -g @catppuccin_application_icon " "

run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

set -g status-left ""
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"

# Point TPM at the XDG-style plugin directory:
# set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/plugins/"

# Initialize TPM
run -b '~/.config/tmux/plugins/tpm/tpm'
